### ISSUE TITLE
add session counter an logout button to the service panel

### ISSUE THREAD

**Issue by criloz** [NebTex/react-typescript-boilerplate#14]
![fixes](https://cloud.githubusercontent.com/assets/1408540/25434854/96251064-2a53-11e7-9b31-c1f0b35c4437.png)

- [x] add session counter like the images, with the adequate bootstrap elements
- [x] session counter should have `your session never expires` login
- [x] add logout button in red, the logout endpoint is /ui/logout

**Comment by Ignusmart** [comment]
@criloz the action to logout is with a `post` method, right?

**Comment by criloz** [comment]
@Ignusmart not,  just `get`

**Comment by criloz** [comment]
@Ignusmart thanks!1
